pipeline {
    agent { label 'docker-worker' }

    environment {
        DOCKER_IMAGE = "miker5904/test"
        DOCKER_CREDENTIALS = credentials('dockerhub')
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/TheTheeMike/nodejs-test.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $DOCKER_IMAGE:latest .'
            }
        }

        stage('Run Tests') {
            steps {
                script {
                    try {
                        sh 'docker run --rm $DOCKER_IMAGE:latest npm test'
                    } catch (err) {
                        error("Tests failed")
                    }
                }
            }
        }

        stage('Push to Docker Hub') {
            when {
                expression { currentBuild.result == null } // only if no errors
            }
            steps {
                sh '''
                    echo "$DOCKER_CREDENTIALS_PSW" | docker login -u "$DOCKER_CREDENTIALS_USR" --password-stdin
                    docker push $DOCKER_IMAGE:latest
                '''
            }
        }
    }

    post {
        failure {
            echo 'Tests failed'
        }
        success {
            echo 'Image pushed to Docker Hub successfully'
        }
    }
}

