pipeline {
    agent { label 'worker' }

    environment {
        DOCKERHUB = credentials('dockerhub')   // from step 7
        IMAGE_NAME = "myapp"                   // change to your app name
        IMAGE_TAG = "latest"
    }

    stages {
        stage('Checkout Code') {
            steps {
                checkout scm   // pulls the repo Jenkins job is linked to
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                  echo "Building Docker image..."
                  docker build -t $DOCKERHUB_USR/$IMAGE_NAME:$IMAGE_TAG .
                '''
            }
        }

        stage('Run Tests') {
            steps {
                script {
                    def status = sh(
                        script: "docker run --rm $DOCKERHUB_USR/$IMAGE_NAME:$IMAGE_TAG npm test",
                        returnStatus: true
                    )
                    if (status != 0) {
                        echo "Tests failed"
                        error("Tests failed")  // stop pipeline here
                    }
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                sh '''
                  echo "$DOCKERHUB_PSW" | docker login -u "$DOCKERHUB_USR" --password-stdin
                  docker push $DOCKERHUB_USR/$IMAGE_NAME:$IMAGE_TAG
                '''
            }
        }
    }
}

